"""A deterministic, clearly-labelled demo fleet.

Why this exists: the measured cohort behind this platform is five NASA
laboratory cells, all of which ran to end of life. A fleet page needs more rows
than that, at a range of ages, to demonstrate ranking, workload bucketing and
replacement horizons at all.

Two constructions, and the choice between them matters
------------------------------------------------------
``derived`` (default when a processed cycle table exists)
    Take the **measured** cells and truncate each at a different point in its
    own life, under a new ``DEMO-`` identifier. The measurements are real, so
    the model scores them in-distribution and the resulting fleet spans healthy
    to critical the way a real fleet does. It is a *re-presentation* of measured
    data — several demo cells share an underlying cell — not new data.

``synthetic``
    Cells from the Milestone 1 physics-informed generator. Used when no
    processed data exists. Note what this actually demonstrates: a model trained
    on the NASA cohort scoring cells from a different generator is
    **extrapolating**, and it shows — every cell comes back with dozens of
    out-of-distribution features and a remaining-life estimate at the clip
    floor. That is the data-quality machinery working, and it is why the
    derived construction is the default rather than a convenience.

Three rules both constructions keep:

1. Deterministic: the same spec always produces the same fleet. A demo that
   changes under the reader is not a demo.
2. ``is_demo_data=True`` travels with every history, into the ingestion result,
   into the snapshot identity, into the summary and into a fleet-level warning.
   There is no code path here that produces data without that flag.
3. Ids are prefixed ``DEMO-``, so they can never be mistaken for a NASA cell id
   (``B0005``) in a report, a log line or a database row.

Nothing here is a claim about any real fleet, and no metric computed on a demo
fleet is a research result.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import numpy as np
import pandas as pd

from battery_rul.config import ExperimentConfig
from battery_rul.data.synthetic import make_synthetic_cycles
from battery_rul.fleet.domain import FleetIdentity
from battery_rul.fleet.ingestion import BatteryHistoryInput, FleetIngestionResult, FleetIngestor
from battery_rul.utils.logging import get_logger

logger = get_logger(__name__)

__all__ = [
    "DEMO_FLEET_ID",
    "DEMO_NOTICE",
    "DERIVED_NOTICE",
    "DemoFleetSpec",
    "demo_fleet_identity",
    "generate_demo_fleet",
    "ingest_demo_fleet",
    "resolve_construction",
]

DEMO_FLEET_ID = "DEMO-FLEET-01"

DEMO_NOTICE = (
    "SYNTHETIC DEMONSTRATION DATA. These cells were generated by the "
    "physics-informed simulator in battery_rul.data.synthetic, seeded "
    "deterministically from their identifiers. They are not measurements, they "
    "do not describe any real fleet, and no number computed from them is a "
    "research result."
)

DERIVED_NOTICE = (
    "DEMONSTRATION FLEET DERIVED FROM MEASURED CELLS. Each cell here is one of "
    "the measured laboratory cells, truncated at a different point in its own "
    "life and given a demo identifier, so that a small cohort can illustrate a "
    "fleet at a range of ages. Several demo cells share an underlying physical "
    "cell. The measurements are real; the fleet is not, and no number computed "
    "from it describes any operator's fleet."
)


@dataclass(frozen=True, slots=True)
class DemoFleetSpec:
    """What a demo fleet should contain.

    The mix is chosen to exercise the fleet layer's branches — healthy cells,
    degraded cells, cells too young to score, cells with a sensor dropout — not
    to resemble any particular operator's fleet.
    """

    fleet_id: str = DEMO_FLEET_ID
    n_batteries: int = 24
    seed: int = 20260813
    #: ``derived`` re-presents the measured cells at different ages; ``synthetic``
    #: generates new ones; ``auto`` prefers derived and falls back to synthetic
    #: when no processed cycle table exists. See the module docstring for why the
    #: default is not the synthetic generator.
    construction: Literal["auto", "derived", "synthetic"] = "auto"
    #: Fraction of cells truncated to below the first scoreable cycle, so the
    #: fleet contains cells that genuinely cannot be scored. Fleet code that only
    #: ever sees complete records is untested code.
    short_history_fraction: float = 0.10
    #: Fraction of cells with a sensor column blanked, to exercise the
    #: missing-feature and data-quality paths.
    missing_sensor_fraction: float = 0.15
    min_cycles: int = 60
    max_cycles: int = 170
    #: Each cell is truncated at a random point in its own life, uniformly in
    #: this range. A real fleet is a mixture of ages: some cells were installed
    #: last month and some are nearly worn out. Without this the whole demo fleet
    #: sits at its final cycle and every cell reports critical, which exercises
    #: none of the ranking, workload or replacement-horizon logic.
    life_fraction_range: tuple[float, float] = (0.30, 1.00)


def resolve_construction(cfg: ExperimentConfig, spec: DemoFleetSpec) -> str:
    """Which construction will actually be used, given what exists on disk."""
    if spec.construction != "auto":
        return spec.construction
    return "derived" if _processed_cycles_path(cfg).is_file() else "synthetic"


def _processed_cycles_path(cfg: ExperimentConfig):
    return cfg.paths.processed_dir / "cycles.parquet"


def generate_demo_fleet(
    cfg: ExperimentConfig, spec: DemoFleetSpec | None = None
) -> list[BatteryHistoryInput]:
    """Build the demo fleet's histories. Deterministic for a given spec."""
    spec = spec or DemoFleetSpec()
    if resolve_construction(cfg, spec) == "derived":
        return _derived_demo_fleet(cfg, spec)
    return _synthetic_demo_fleet(cfg, spec)


def _derived_demo_fleet(cfg: ExperimentConfig, spec: DemoFleetSpec) -> list[BatteryHistoryInput]:
    """Measured cells, truncated at different points in their own lives.

    Cells are assigned round-robin, so a fleet of 24 built from 5 measured cells
    uses each of them, and each demo cell is cut at a different life fraction.
    The result spans healthy to critical because the underlying cells do — and
    the model scores it in-distribution, which the synthetic construction does
    not.
    """
    from battery_rul.fleet.ingestion import _drop_label_columns

    source = _processed_cycles_path(cfg)
    frame = _drop_label_columns(pd.read_parquet(source))
    sources = sorted(frame["battery_id"].astype(str).unique())
    if not sources:
        raise ValueError(f"{source} contains no batteries to derive a demo fleet from.")

    rng = np.random.default_rng(spec.seed)
    low, high = spec.life_fraction_range
    histories: list[BatteryHistoryInput] = []

    for index in range(spec.n_batteries):
        battery_id = f"DEMO-{index + 1:04d}"
        origin = sources[index % len(sources)]
        cell = (
            frame.loc[frame["battery_id"].astype(str) == origin]
            .sort_values("cycle_index")
            .reset_index(drop=True)
            .copy()
        )
        life_fraction = float(rng.uniform(low, high))
        kept = max(int(round(life_fraction * len(cell))), 1)
        cell = cell.head(kept)
        cell["battery_id"] = battery_id
        cell["dataset"] = "demo_derived"

        warnings = [
            f"Demo cell derived from measured cell {origin}, truncated at "
            f"{life_fraction:.0%} of its recorded life ({kept} of "
            f"{int((frame['battery_id'].astype(str) == origin).sum())} cycles)."
        ]
        if index >= len(sources):
            warnings.append(
                "This demo cell shares an underlying physical cell with another demo "
                "cell in the same fleet; the fleet size is not a count of distinct cells."
            )

        # A few cells are degraded further, so the demo exercises the
        # insufficient-data and missing-feature paths rather than only the happy one.
        draw = rng.random()
        if draw < spec.short_history_fraction:
            cell = cell.head(max(int(cfg.features.drop_warmup_cycles * 0.6), 3)).copy()
            warnings.append(
                "Demo cell cut below the first scoreable cycle, to exercise the "
                "insufficient-data path."
            )
        elif draw < spec.short_history_fraction + spec.missing_sensor_fraction:
            for column in ("internal_resistance_ohm", "temperature_max_c"):
                if column in cell.columns:
                    cell[column] = np.nan
            warnings.append(
                "Demo cell with two sensor channels blanked, to exercise the "
                "missing-feature path."
            )

        histories.append(
            BatteryHistoryInput(
                battery_id=battery_id,
                history=cell.reset_index(drop=True),
                source="demo_derived",
                is_synthetic=True,
                warnings=warnings,
            )
        )

    logger.warning(
        "Generated a DERIVED demo fleet of %d cells from %d measured cell(s) (%s). %s",
        len(histories),
        len(sources),
        spec.fleet_id,
        DERIVED_NOTICE,
    )
    return histories


def _synthetic_demo_fleet(cfg: ExperimentConfig, spec: DemoFleetSpec) -> list[BatteryHistoryInput]:
    """Cells from the physics-informed generator.

    Used when no measured data exists. Expect the out-of-distribution flags to
    fire: a model fitted on the NASA cohort scoring cells from this generator is
    extrapolating, and the platform says so rather than hiding it.
    """
    rng = np.random.default_rng(spec.seed)
    histories: list[BatteryHistoryInput] = []

    for index in range(spec.n_batteries):
        battery_id = f"DEMO-{index + 1:04d}"
        # Seeded from the index, not from the shared rng's state, so a change to
        # the fleet size does not silently change every other cell.
        cell_seed = spec.seed + index
        n_cycles = int(rng.integers(spec.min_cycles, spec.max_cycles + 1))
        frame = make_synthetic_cycles(
            battery_id,
            n_cycles=n_cycles,
            nominal_capacity_ah=cfg.data.nominal_capacity_ah,
            eol_threshold=cfg.data.eol_threshold,
            seed=cell_seed,
        )
        frame["dataset"] = "synthetic_demo"

        warnings: list[str] = []
        # Age the cell: keep only the first `life_fraction` of its record, so
        # the fleet spans installation dates the way a real one does.
        low, high = spec.life_fraction_range
        life_fraction = float(rng.uniform(low, high))
        kept = max(int(round(life_fraction * len(frame))), 1)
        if kept < len(frame):
            frame = frame.head(kept).copy()
            warnings.append(
                f"Demo cell truncated at {life_fraction:.0%} of its simulated life, so "
                "the demo fleet contains cells of different ages."
            )

        draw = rng.random()
        if draw < spec.short_history_fraction:
            keep = max(int(cfg.features.drop_warmup_cycles * 0.6), 3)
            frame = frame.head(keep).copy()
            warnings.append(
                "Demo cell truncated to a short history, to exercise the insufficient-data path."
            )
        elif draw < spec.short_history_fraction + spec.missing_sensor_fraction:
            for column in ("internal_resistance_ohm", "temperature_max_c"):
                if column in frame.columns:
                    frame[column] = np.nan
            warnings.append(
                "Demo cell with two sensor channels blanked, to exercise the "
                "missing-feature path."
            )

        histories.append(
            BatteryHistoryInput(
                battery_id=battery_id,
                history=frame.reset_index(drop=True),
                source="synthetic_demo",
                is_synthetic=True,
                warnings=warnings,
            )
        )

    logger.warning(
        "Generated a SYNTHETIC demo fleet of %d cells (%s). %s",
        len(histories),
        spec.fleet_id,
        DEMO_NOTICE,
    )
    return histories


def demo_fleet_identity(
    spec: DemoFleetSpec | None = None, *, construction: str = "synthetic"
) -> FleetIdentity:
    """The identity block for a demo fleet, naming how it was constructed."""
    spec = spec or DemoFleetSpec()
    derived = construction == "derived"
    return FleetIdentity(
        fleet_id=spec.fleet_id,
        name=f"Demonstration fleet ({'derived from measured cells' if derived else 'synthetic'})",
        description=(
            f"{spec.n_batteries} cells, seed {spec.seed}, "
            + (
                "each a measured cell truncated at a different point in its life."
                if derived
                else "each generated deterministically by the physics-informed simulator."
            )
        ),
        source="demo_derived" if derived else "synthetic_demo",
        is_demo_data=True,
        data_notice=DERIVED_NOTICE if derived else DEMO_NOTICE,
    )


def ingest_demo_fleet(
    cfg: ExperimentConfig, spec: DemoFleetSpec | None = None
) -> tuple[FleetIngestionResult, list[BatteryHistoryInput]]:
    """Generate and ingest the demo fleet, so it takes the same validated path.

    Deliberately routed through :class:`FleetIngestor` rather than handed
    straight to inference: demo data that skips validation would not exercise
    the code the real path runs, which is most of the reason to have a demo.
    """
    spec = spec or DemoFleetSpec()
    construction = resolve_construction(cfg, spec)
    notice = DERIVED_NOTICE if construction == "derived" else DEMO_NOTICE
    source = "demo_derived" if construction == "derived" else "synthetic_demo"

    histories = generate_demo_fleet(cfg, spec)
    frame = pd.concat(
        [h.history.assign(battery_id=h.battery_id) for h in histories], ignore_index=True
    )
    result, ingested = FleetIngestor(cfg=cfg).from_frame(
        spec.fleet_id,
        frame,
        source=source,
        is_synthetic=True,
        max_batteries=max(spec.n_batteries, cfg.fleet.max_batteries_per_batch),
    )
    warnings_by_id = {h.battery_id: h.warnings for h in histories}
    for item in ingested:
        item.is_synthetic = True
        item.source = source
        item.warnings = [*warnings_by_id.get(item.battery_id, []), *item.warnings]
    result.warnings.append(notice)
    return result, ingested
